version: '3.4'
services:
  jphoto.mysql:
    image: mysql:5.7
    container_name: jphoto_mysql.bordozer.sql
    environment:
      MYSQL_DATABASE:  'jphoto_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'root'
      MYSQL_RANDOM_ROOT_PASSWORD: 'root'
    ports:
      - '3300:3306'
    restart: always
    volumes:
      - jphoto_db_mysql:/var/lib/minesql/data:cached
    command: --sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'

volumes:
  jphoto_db_mysql:
    driver: 'local'
